import { ArrowRight, BarChart3, CircleDollarSign, Image, Network } from 'lucide-react';

export default function FeatureShowcase(){
 return <section className="feature-showcase" aria-labelledby="feature-showcase-title">
  <header><span>FEATURES</span><h2 id="feature-showcase-title">Built for <em>smarter advertising decisions.</em></h2><p>Everything you need to turn campaign data into clear, confident actions.</p></header>
  <div className="feature-card-grid">
   <article className="capability-card"><div className="capability-head"><span><BarChart3/></span><div><h3>Campaign Intelligence</h3><p>Identify performance changes and understand what’s driving them.</p></div></div><div className="mini-campaign"><div><span><small>Conversions</small><b>18.6K</b><em>↓ 32%</em></span><span><small>ROAS (Avg)</small><b>4.2×</b><em className="positive">↑ 12%</em></span></div><svg viewBox="0 0 310 105" aria-hidden="true"><path className="mini-grid" d="M5 30H305M5 62H305M5 94H305"/><path className="mini-muted" d="M8 80 L58 44 L108 73 L158 63 L208 82 L258 68 L302 28"/><path className="mini-main" d="M8 70 L58 51 L108 75 L158 82 L208 71 L258 60 L302 22"/><circle cx="158" cy="82" r="4"/></svg><span className="mini-alert">Performance dropped · creative CTR ↓ 28%</span></div><a href="#understand">Explore campaign intelligence <ArrowRight/></a></article>
   <article className="capability-card"><div className="capability-head"><span><CircleDollarSign/></span><div><h3>Budget Optimisation</h3><p>Find scaling opportunities and allocate spend more effectively.</p></div></div><div className="mini-budget"><small>SCALE OPPORTUNITY</small><h4>Scale Google Search</h4><p>ROAS is above target and delivery may be limited by budget.</p><div><span><small>ROAS</small><b>6.1×</b><em>↑ 38%</em></span><span><small>Budget utilisation</small><b>62%</b><i><u/></i></span></div></div><a href="#recommend">Explore budget optimisation <ArrowRight/></a></article>
   <article className="capability-card"><div className="capability-head"><span><Image/></span><div><h3>Creative Intelligence</h3><p>Discover winning creatives and new testing opportunities across platforms.</p></div></div><div className="creative-strip"><span className="creative-a"><i>▶</i><b>DEMO</b></span><span className="creative-b"><b>PRODUCT</b></span><span className="creative-c"><b>STORY</b></span><span className="creative-more">+3</span></div><div className="creative-stats"><span><small>CTR</small><b>3.2×</b><em>↑ 230%</em></span><span><small>CVR</small><b>2.1×</b><em>↑ 110%</em></span><span><small>CPA</small><b>−28%</b><em>↓ 28%</em></span></div><a href="#learn">Explore creative intelligence <ArrowRight/></a></article>
   <article className="capability-card"><div className="capability-head"><span><Network/></span><div><h3>Cross-channel Analysis</h3><p>See the bigger picture with unified insights from all your platforms.</p></div></div><div className="channel-map"><span className="channel google">G</span><span className="channel meta">∞</span><span className="channel tiktok">♪</span><i/><b/></div><div className="connected-note"><BarChart3/><p><b>Connected insights</b><small>Understand how platforms, campaigns and creatives influence each other.</small></p></div><a href="#observe">Explore cross-channel analysis <ArrowRight/></a></article>
  </div>
 </section>;
}
