import { ArrowRight, BarChart3, CircleDollarSign, Image, Megaphone, Network, Play } from 'lucide-react';
import { motion, useReducedMotion } from 'framer-motion';

const inputs=[{name:'Meta',detail:'Campaigns · Ads · Insights',mark:'∞',tone:'meta'},{name:'Google',detail:'Search · Display · YouTube',mark:'G',tone:'google'},{name:'TikTok',detail:'Ads · Creatives · Performance',mark:'♪',tone:'tiktok'},{name:'Campaigns',detail:'Performance · Goals · Audiences',Icon:CircleDollarSign},{name:'Creatives',detail:'Assets · Variations · CTR',Icon:Megaphone}];
const outputs=[{name:'Campaign Intelligence',detail:'Spot changes, act faster',Icon:BarChart3},{name:'Budget Optimisation',detail:'Allocate spend smarter',Icon:CircleDollarSign},{name:'Creative Intelligence',detail:'Discover what performs',Icon:Image},{name:'Cross-channel Analysis',detail:'See the bigger picture',Icon:Network}];

export default function Hero(){
 const reduceMotion=useReducedMotion();
 return <section className="hero hero--connected" id="product"><div className="connected-hero-copy"><div className="connected-eyebrow">AI-POWERED MARKETING INTELLIGENCE</div><h1>Every signal connected.<br/>Every <span>decision clearer.</span></h1><p>Unify campaign, creative, and budget intelligence across platforms to uncover opportunities, understand performance shifts, and move with confidence.</p><div className="connected-actions"><a className="button button--primary" href="#product-preview">Explore AdPilot <ArrowRight size={17}/></a><a className="connected-demo" href="#demo"><span><Play size={14} fill="currentColor"/></span>Book a demo</a></div></div><div className="connected-system" aria-label="Advertising signals connect through AdPilot into actionable intelligence"><svg viewBox="0 0 1440 510" preserveAspectRatio="none" aria-hidden="true"><g className="connected-lines">{[95,175,255,335,415].map((y,i)=><motion.path key={'l'+y} d={`M115 ${y} C300 ${y} 360 ${250+(i-2)*13} 650 255`} initial={reduceMotion?false:{pathLength:0,opacity:0}} animate={{pathLength:1,opacity:1}} transition={{duration:reduceMotion?0:1.3,delay:i*.08}}/>)}{[118,215,312,409].map((y,i)=><motion.path key={'r'+y} d={`M790 255 C1050 ${250+(i-1.5)*14} 1120 ${y} 1325 ${y}`} initial={reduceMotion?false:{pathLength:0,opacity:0}} animate={{pathLength:1,opacity:1}} transition={{duration:reduceMotion?0:1.3,delay:.25+i*.08}}/>)}<path className="connected-beam" d="M650 255H790"/></g>{[[310,150],[380,222],[450,300],[520,238],[580,330],[860,220],[940,280],[1030,185],[1120,325]].map(([x,y],i)=><circle key={i} cx={x} cy={y} r={i%3===0?4:2.5}/>)}</svg><div className="input-stack">{inputs.map(({name,detail,mark,tone,Icon})=><div className="connected-card input-card" key={name}><span className={'connected-icon '+(tone||'')}>{Icon?<Icon size={21}/>:mark}</span><div><b>{name}</b><small>{detail}</small></div></div>)}</div><div className="adpilot-core"><span className="core-orbit"/><span className="core-mark">A</span><small>ADPILOT</small></div><div className="output-stack">{outputs.map(({name,detail,Icon})=><div className="connected-card output-card" key={name}><span className="connected-icon intelligence"><Icon size={21}/></span><div><b>{name}</b><small>{detail}</small></div></div>)}</div></div></section>;
}
